[package]
name = "ray_tracing"
version = "0.1.1"
authors = ["zerax"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 1

[dependencies]
image="*"
rand="*"